### ISSUE TITLE
First time start server show some error

### ISSUE THREAD

**Issue by AuthMe** [TacoSpigot/TacoSpigot#25]
```
Loading TacoSpigot configuration from: taco.yml
Loading libraries, please wait...
2016-04-06 22:58:02,426 WARN Unable to instantiate org.fusesource.jansi.WindowsA
nsiOutputStream
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.
internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSu
pport.java:50)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(Wind
owsTerminal.java:204)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTermina
l.java:82)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFact
ory.java:101)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory
.java:158)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(Consol
eReader.java:229)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(Consol
eReader.java:221)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(Consol
eReader.java:213)
        at net.minecraft.server.v1_9_R1.MinecraftServer.<init>(MinecraftServer.j
ava:145)
        at net.minecraft.server.v1_9_R1.DedicatedServer.<init>(DedicatedServer.j
ava:46)
        at net.minecraft.server.v1_9_R1.MinecraftServer.main(MinecraftServer.jav
a:992)
        at org.bukkit.craftbukkit.Main.main(Main.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.destroystokyo.paperclip.Paperclip.main(Paperclip.java:177)

[22:58:14 INFO]: Starting minecraft server version 1.9.2
[22:58:14 INFO]: Loading properties
[22:58:14 INFO]: You need to agree to the EULA in order to run the server. Go to
 eula.txt for more info.
[22:58:14 INFO]: Stopping server
>[WARN] Task failed
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.
internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.setConsoleMode(WindowsSu
pport.java:60)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.setConsoleMode(Wind
owsTerminal.java:208)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.restore(WindowsTerm
inal.java:95)
        at org.bukkit.craftbukkit.libs.jline.TerminalSupport$1.run(TerminalSuppo
rt.java:52)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.runTasks(Shu
tdownHooks.java:66)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.access$000(S
hutdownHooks.java:22)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks$1.run(Shutdo
wnHooks.java:47)
```

**Comment by Techcable** [comment]
@RoboMWM reported this a _long_ time ago, and I still have no idea what could possibly be causing this.

**Comment by RoboMWM** [comment]
Yet you close the issue. >_>

**Comment by Techcable** [comment]
try the [raw (non-paperclip) jar](https://transfer.sh/krNIQ/tacospigot-raw.jar)
Could you also try it @RoboMWM and @MClausz?

**Comment by MClausz** [comment]
PaperSpigot build 443 (1.8.8) also have this issue, and is fixed since 1.9 update (444, 445). You can ask them for help.
I've looked over comits list and still have no idea which file to edit to fix it.
https://ci.destroystokyo.com/job/PaperSpigot/444/

**Comment by Techcable** [comment]
@MClausz did you try the file I linked you?
I suspect it may be a problem with Paperclip.

**Comment by MClausz** [comment]
I'll try it later
I think something went wrong while patching the original file, in the nms.MinecraftServer

**Comment by sgdc3** [comment]
what about --nojline ? xD

**Comment by sgdc3** [comment]
![nojline](https://cloud.githubusercontent.com/assets/8779252/16378515/955c5b4a-3c6c-11e6-8904-ea9009fd1796.PNG)

**Comment by sgdc3** [comment]
If you install Visual C++ it shoud work fine.

**Comment by RoboMWM** [comment]
@sgdc3 iirc nojline results in weird console behavior at times. Visual C++ has nothing to do with this, as paper/spigot/CB can use jline just fine with same setup. I've had a lot less time this summer than I expected, but I'll try to fire up tacospigot locally if nobody else has tested this yet.
