### ISSUE TITLE
1.8 Crash

### ISSUE THREAD

**Issue by sgdc3** [TacoSpigot/TacoSpigot#28]
```
[21:22:24] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at java.util.TreeMap.rotateLeft(TreeMap.java:2220) ~[?:1.8.0_77]
	at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2287) ~[?:1.8.0_77]
	at java.util.TreeMap.put(TreeMap.java:582) ~[?:1.8.0_77]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:1.8.0_77]
	at org.bukkit.craftbukkit.v1_8_R3.util.HashTreeSet.add(HashTreeSet.java:75) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:586) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:455) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"a670e7e"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a670e7e"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by Techcable** [comment]
Looks like corrupted chunks/entities.

**Comment by sgdc3** [comment]
Would it be possible to remove the entity or unload the chunk instead of stopping the server? ;)

**Comment by Techcable** [comment]
Yes, but I have no intention of fixing it.
You should just fix the corrupted chunk.

**Comment by sgdc3** [comment]
Yeah but how can i find it on a 30000*30000 20GB map? xD

**Comment by sgdc3** [comment]
@techable Do you know any tips?
