### ISSUE TITLE
Another 1.8 Crash

### ISSUE THREAD

**Issue by sgdc3** [TacoSpigot/TacoSpigot#31]
```
[20:09:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:841) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_8_R3.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:297) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.processChunkGC(CraftWorld.java:1403) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:273) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    ... 4 more
[20:09:56] [Server thread/ERROR]:   Cause of unexpected exception was
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_8_R3.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:297) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.processChunkGC(CraftWorld.java:1403) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:273) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by sgdc3** [comment]
With useArraysForBlockStates: false it seems to work fine

**Comment by Techcable** [comment]
How often does this happen?

**Comment by sgdc3** [comment]
Evey 10 min with 15 - 20 players

**Comment by sgdc3** [comment]
I can confirm that with useArraysForBlockStates disabled it works fine.

**Comment by sgdc3** [comment]
:( Just happened with useArrays set to false.

```
[15:05:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:841) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.util.ConcurrentModificationException
	at org.bukkit.craftbukkit.v1_8_R3.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:297) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_77]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_77]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SpawnerCreature.getEntityCount(SpawnerCreature.java:31) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:130) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	... 4 more
[15:05:38] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException
	at org.bukkit.craftbukkit.v1_8_R3.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:297) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_77]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_77]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SpawnerCreature.getEntityCount(SpawnerCreature.java:31) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:130) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by sgdc3** [comment]
@Techcable bump :(

**Comment by sgdc3** [comment]
@Techcable Please, how can i fix this?

**Comment by Techcable** [comment]
Its an issue with the recent fix for the Spigot Mob Spawn Logic :(

**Comment by sgdc3** [comment]
So reverting 0487e626f2940d3458ff1ddd4dd0cb2cc093dff8 should fix the issue, right? @Techcable

**Comment by Techcable** [comment]
Yes, but  that would un-fix the existing issue.
I think this is a deeper problem since it doesn't happen with 1.9, and I have the exact same implementation as paper.

**Comment by Techcable** [comment]
This may very well be a plugin issue. It might actually be concurrent modification.
What plugins do you have?

**Comment by sgdc3** [comment]
Probably MythicMobs fault :/
