### ISSUE TITLE
[1.10.2] Encountered an unexpected exception - Crash

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#42]
```
[14:59:20] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Exception while ticking a block
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:860) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"af9406f"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.a(BlockTripwireHook.java:185) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.b(BlockTripwireHook.java:195) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:746) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:250) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched.jar:git-TacoSpigot-"af9406f"]
    ... 4 more
[14:59:20] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.a(BlockTripwireHook.java:185) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.b(BlockTripwireHook.java:195) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:746) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:250) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) ~[patched.jar:git-TacoSpigot-"af9406f"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"af9406f"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

```
>ver
[15:06:18 INFO]: This server is running Paper version git-TacoSpigot-"af9406f" (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[15:06:18 INFO]: Checking version, please wait...
[15:06:19 INFO]: You are 3 commit(s) behind
```

**Comment by melinstagibson** [comment]
Was about to post the same issue.

i guess this means the block array thing has an issue with tripwires

crashes the server around once a day for me

**Comment by L4BORG** [comment]
Crash our server every ~2h for us...

```
useArraysForBlockStates: false
useArraysForDatawatcher: false
```

solved the issue... kinda (it's not crashing anymore lol).

**Comment by Techcable** [comment]
Please reopen this issue if this keeps happening.
