### ISSUE TITLE
[1.10.2] IllegalArgumentException: Cannot set property BlockStateBoolean("attached") as it does not exist in BlockStateList

### ISSUE THREAD

**Issue by 1434967947** [TacoSpigot/TacoSpigot#47]
```
32:58] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.a(BlockTripwireHook.java:185) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwire.e(BlockTripwire.java:92) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwire.onPlace(BlockTripwire.java:60) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:190) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:534) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:893) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    ... 5 more
[13:33:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Exception while ticking a block
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:859) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.a(BlockTripwireHook.java:185) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.b(BlockTripwireHook.java:195) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:754) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:258) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:848) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    ... 4 more
[13:33:33] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot set property BlockStateBoolean{name=attached, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateList{block=minecraft:tripwire, properties=[attached, disarmed, east, north, powered, south, west]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.a(BlockTripwireHook.java:185) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.BlockTripwireHook.b(BlockTripwireHook.java:195) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:754) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:258) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:848) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"d9d17b4"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[13:33:33] [Server thread/ERROR]: This crash report has been saved to: E:\mc\skyblock\.\crash-reports\crash-2016-08-11_13.33.33-server.txt
[13:33:33] [Server thread/INFO]: Stopping server
[13:33:33] [Server thread/INFO]: [TreasureChest] Disabling TreasureChest v8.4.1
[13:33:33] [Server thread/INFO]: [HolographicDisplays] D
```

**Comment by Techcable** [comment]
Appears to be the same as #42

**Comment by mcarey10** [comment]
I've been facing this bug as well.

**Comment by mcarey10** [comment]
Update: previously a way around this bug was to disable "useArraysForBlockStates" and "useArraysForDatawatcher" however that doesn't seem to be the case. Although those changes did seem to prevent crashes as frequently, my server just crashed with the same error even with both of those 'array' options set to false.

**Comment by Techcable** [comment]
What's the stack trace with them set to false?

**Comment by 1434967947** [comment]
at least my server goes well when i set them to false
