### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by sgdc3** [TacoSpigot/TacoSpigot#60]
```
java.lang.NullPointerException
        at org.bukkit.Bukkit.getVersion(Bukkit.java:98)
        at net.techcable.tacospigot.TacoVersioning.currentVersion(TacoVersioning.java:26)
        at org.bukkit.craftbukkit.Main.main(Main.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.destroystokyo.paperclip.Paperclip.main(Paperclip.java:177)
```

**Comment by Techcable** [comment]
I should probably have tested my changes 💩

**Comment by sgdc3** [comment]
lol

**Comment by sgdc3** [comment]
Any news ? :)
