### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by MCTyler** [TacoSpigot/TacoSpigot#7]
What kind of issues do you want on here? It breaks LWC and GriefPrevention, but I'm sure you guys know that. I was on Spigot discussing PaperClip then I got pummeled so I came over here.

**Comment by Techcable** [comment]
How does it break LWC and grief prevention?

**Comment by MCTyler** [comment]
I downloaded taco and put it on the server ran the start script and got a ton of errors...Am I doing it wrong?

**Comment by Techcable** [comment]
What errors?

**Comment by MCTyler** [comment]
I deleted them I'll run it again...LWC simply says is it up to date...I will copy...

**Comment by MCTyler** [comment]
`[17:36:25] [Server thread/INFO]: [LWC] Enabling LWC v1.7.2
[17:36:25] [Server thread/INFO]: [LWC] Connecting to SQLite
[17:36:25] [Server thread/WARN]: java.lang.ClassNotFoundException: org.sqlite.JDBC
[17:36:25] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:36:25] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:36:25] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:36:25] [Server thread/WARN]: 	at com.griefcraft.sql.Database.connect(Database.java:237)
[17:36:25] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1698)
[17:36:25] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:219)
[17:36:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:36:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[17:36:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[17:36:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358)
[17:36:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[17:36:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:204)
[17:36:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[17:36:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:36:25] [Server thread/ERROR]: Error occurred while enabling LWC v1.7.2 (Is it up to date?)
java.lang.NullPointerException
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:903) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1711) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:219) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:204) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by MCTyler** [comment]
`[17:36:33] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to GriefPrevention v13.9
org.bukkit.event.EventException
	at net.techcable.tacospigot.EventExecutorFactory$MethodHandleEventExecutor.execute(EventExecutorFactory.java:84) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:305) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1020) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:990) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItem(CraftWorld.java:336) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.maxgamer.quickshop.Shop.DisplayItem.spawn(DisplayItem.java:43) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.Shop.ContainerShop.checkDisplay(ContainerShop.java:626) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.Shop.ContainerShop.onLoad(ContainerShop.java:647) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:232) [QuickShop-0.9.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassCastException: Cannot cast org.bukkit.event.entity.ItemSpawnEvent to org.bukkit.event.entity.CreatureSpawnEvent
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[?:1.8.0_72]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[?:1.8.0_72]
	at net.techcable.tacospigot.EventExecutorFactory$MethodHandleEventExecutor.execute(EventExecutorFactory.java:82) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	... 23 more
[17:36:33] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to WorldGuard v6.1
org.bukkit.event.EventException
	at net.techcable.tacospigot.EventExecutorFactory$MethodHandleEventExecutor.execute(EventExecutorFactory.java:84) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:305) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1020) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:990) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItem(CraftWorld.java:336) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.maxgamer.quickshop.Shop.DisplayItem.spawn(DisplayItem.java:43) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.Shop.ContainerShop.checkDisplay(ContainerShop.java:626) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.Shop.ContainerShop.onLoad(ContainerShop.java:647) [QuickShop-0.9.8.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:232) [QuickShop-0.9.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-859e8d6-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassCastException: Cannot cast org.bukkit.event.entity.ItemSpawnEvent to org.bukkit.event.entity.CreatureSpawnEvent
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[?:1.8.0_72]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[?:1.8.0_72]
	at net.techcable.tacospigot.EventExecutorFactory$MethodHandleEventExecutor.execute(EventExecutorFactory.java:82) ~[patched.jar:git-TacoSpigot-859e8d6-unknown]
	... 23 more

And on and on and on......`

**Comment by Techcable** [comment]
Should be fixed by 6dd0ac8bff831bf46f426ec1228ff5043b46f75e

**Comment by Techcable** [comment]
In otherwords update to [build 10](https://ci.techcable.net/job/TacoSpigot/10/) once its complete.

**Comment by MCTyler** [comment]
I did not download the yellow flagged build, I guess I need it...Sry

**Comment by MCTyler** [comment]
Ok I will wait for #10 to build....

**Comment by MCTyler** [comment]
Still breaks LWC but a lot less errors...I gotta have LWC People have so many things protected with it.
`[17:58:59] [Server thread/INFO]: [LWC] Enabling LWC v1.7.2
[17:58:59] [Server thread/INFO]: [LWC] Connecting to SQLite
[17:58:59] [Server thread/WARN]: java.lang.ClassNotFoundException: org.sqlite.JDBC
[17:58:59] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:58:59] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:58:59] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:58:59] [Server thread/WARN]: 	at com.griefcraft.sql.Database.connect(Database.java:237)
[17:58:59] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1698)
[17:58:59] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:219)
[17:58:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:58:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[17:58:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[17:58:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358)
[17:58:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[17:58:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:204)
[17:58:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[17:58:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:58:59] [Server thread/ERROR]: Error occurred while enabling LWC v1.7.2 (Is it up to date?)
java.lang.NullPointerException
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:903) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1711) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:219) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:358) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:204) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-6dd0ac8-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by MCTyler** [comment]
Seems like a flatfile error, has then been tested with the flatfile instead of MySql?

**Comment by MCTyler** [comment]
I wonder if I can import the current DB in MySql and use it that way? I will have to look on EntityLWC.

**Comment by MCTyler** [comment]
Just forget it...your supporters on Spigot make me hate this whole thing....Good Luck!

**Comment by Techcable** [comment]
Uh, okay.
Anyways, that issue is with the plugin.
