### ISSUE TITLE
Server crash 1.8.8

### ISSUE THREAD

**Issue by voodootje0** [TacoSpigot/TacoSpigot#74]
```Time: 8/10/17 6:53 PM
Description: Exception ticking world

java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at java.util.TreeSet.first(TreeSet.java:394)
	at org.bukkit.craftbukkit.v1_8_R3.util.HashTreeSet.first(HashTreeSet.java:114)
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:639)
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at java.util.TreeSet.first(TreeSet.java:394)
	at org.bukkit.craftbukkit.v1_8_R3.util.HashTreeSet.first(HashTreeSet.java:114)
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:639)
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249)
```

I really don't know why this is happening, it just crashes randomly.

Taco.yml
```
config-version: 1
useArraysForBlockStates: false
world-settings:
  default:
    verbose: false
    hopper:
      fire-InventoryMoveItemEvent: false
      push-based: false
    armor-stand:
      optimize-movement: true
    grass-ignores-light: false
    allow-non-player-entities-on-scoreboards: false
    redstone-fire-BlockPhysicsEvent: false
```

**Comment by factionsftwmc** [comment]
I may be a bit late, but this happened to me today so I decided to look into it. This was my error, similar if not the same to this report.

> [13:28:12] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:841) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_151]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_151]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_151]
	at org.bukkit.craftbukkit.v1_8_R3.util.HashTreeSet.first(HashTreeSet.java:114) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:639) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	... 4 more
[13:28:12] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_151]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_151]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_151]
	at org.bukkit.craftbukkit.v1_8_R3.util.HashTreeSet.first(HashTreeSet.java:114) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:639) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [TacoSpigot.jar:git-TacoSpigot-"c2835df"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

The issue appears to be the way the sets in the HashTreeSet are maintained. HashTreeSet contains a HashSet and a TreeSet that it simulataneously maintains however, HashSet and TreeSet have different implementations of insert/remove as explained [here](https://stackoverflow.com/questions/16970210/java-treeset-remove-and-contains-not-working). Since it does not always remove/insert the same it causes variations in size between the sets, however I have not been able to pin down what conditions have to be met for this to occur which is making it difficult to reproduce.
