### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by BenTheNoble** [TacoSpigot/TacoSpigot#91]
Everytime I try to run TacoSpigot I get this:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.destroystokyo.paperclip.Paperclip.main(Paperclip.java:177)
Caused by: java.lang.NullPointerException
        at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1413)
        at org.bukkit.craftbukkit.Main.main(Main.java:23)
        ... 5 more

**Comment by ArtelGG** [comment]
Downgrade to Java 8.
